all:
  children:
    weblogic_servers:
      hosts:
        weblogic:
          ansible_host: 192.168.56.200
          ansible_python_interpreter: /usr/bin/python3.11

    database_servers:
      hosts:
        database:
          ansible_host: 192.168.56.201
          ansible_python_interpreter: /usr/bin/python3.11
